apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: game-config
            - secretRef:
                name: game-secrets
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15  # Wait 15s for NestJS to boot before asking "Are you alive?"
            periodSeconds: 10        # Check every 10s
            failureThreshold: 3      # If it fails 3 times (30s), kill it.

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10  # Wait 10s before checking "Can you take traffic?"
            periodSeconds: 5           # Check every 5s
            successThreshold: 1      # If it says "OK" once, open the gates!
            failureThreshold: 3      # If it fails 3 times, close the gates.

              
          
